nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^.*$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Autorization', 'origin', 'accept', 'bearer']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^http://pixelforce.tk:3000/':
            allow_origin: ['https://pixelforce.tk']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^https://redirectmercure.tk/':
            allow_origin: ['https://pixelforce.tk']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^https://pixelforce.tk/':
            allow_origin: ['https://pixelforce.tk:3000', 'https://redirectmercure.tk']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

        