twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        # pour spécifier le namespace des image. Exemple d'utilisation : email.image('@images/logo.png')
        '%kernel.project_dir%/assets/images': images

when@test:
    twig:
        strict_variables: true
